COMMODITIES = [
    "Ajwan",
    "Alsandikai",
    "Amaranthus",
    "Amla(Nelli Kai)",
    "Amranthas Red",
    "Anthorium",
    "Apple",
    "Arecanut(Betelnut/Supari)",
    "Arhar Dal(Tur Dal)",
    "Arhar(Tur/Red Gram)(Whole)",
    "Asgand",
    "Ashgourd",
    "Ashwagandha",
    "Bajra(Pearl Millet/Cumbu)",
    "Banana",
    "Banana - Green",
    "Barley(Jau)",
    "Beans",
    "Beetroot",
    "Bengal Gram Dal(Chana Dal)",
    "Bengal Gram(Gram)(Whole)",
    "Bhindi(Ladies Finger)",
    "Bitter gourd",
    "Black Gram Dal(Urd Dal)",
    "Black Gram(Urd Beans)(Whole)",
    "Black pepper",
    "Bottle gourd",
    "Brinjal",
    "Cabbage",
    "Capsicum",
    "Carrot",
    "Castor Seed",
    "Cauliflower",
    "Chikoos(Sapota)",
    "Chili Red",
    "Chilly Capsicum",
    "Cluster beans",
    "Coconut",
    "Colacasia",
    "Copra",
    "Coriander(Leaves)",
    "Cotton",
    "Cowpea(Veg)",
    "Cucumbar(Kheera)",
    "Cummin Seed(Jeera)",
    "Drumstick",
    "Dry Chillies",
    "Elephant Yam(Suran)",
    "Field Pea",
    "Garlic",
    "Ginger(Dry)",
    "Ginger(Green)",
    "Green Avare (W)",
    "Green Chilli",
    "Green Gram Dal(Moong Dal)",
    "Green Gram(Moong)(Whole)",
    "Guar",
    "Guava",
    "Ground Nut Seed",
    "Groundnut",
    "Jack Fruit",
    "Jowar(Sorghum)",
    "Jute",
    "Kabuli Chana(Chickpeas-White)",
    "Knool Khol",
    "Lemon",
    "Lentil(Masur)(Whole)",
    "Maize",
    "Mango",
    "Methi(Leaves)",
    "Mint(Pudina)",
    "Mousambi(Sweet Lime)",
    "Mustard",
    "Neem Seed",
    "Onion",
    "Orange",
    "Paddy(Dhan)(Basmati)",
    "Paddy(Dhan)(Common)",
    "Papaya",
    "Peas Wet",
    "Pineapple",
    "Potato",
    "Pumpkin",
    "Raddish",
    "Ragi (Finger Millet)",
    "Rice",
    "Ridgeguard(Tori)",
    "Rubber",
    "Sesamum(Sesame,Gingelly,Til)",
    "Snakeguard",
    "Soyabean",
    "Spinach",
    "Sweet Potato",
    "Tapioca",
    "Tender Coconut",
    "Tobacco",
    "Tomato",
    "Turmeric",
    "Water Melon",
    "Wheat"
]