class AppStrings {
  static const Map<String, Map<String, String>> data = {
    "en": {
      "login": "Login",
      "signup": "Sign Up",
      "welcome_back": "Welcome Back",
      "create_account": "Create Account",
      "phone": "Phone",
      "password": "Password",
      "name": "Name",
      "logout": "Logout",
      "profile": "Profile",
      "save_changes": "Save Changes",
      "security": "Security",
      "change_password": "Change Password",
      "home": "Home",
      "chat": "Chat",
      "market": "Market",
      "pest": "Pest",
      "pest_analyzer": "Pest Analyzer",
      "upload_leaf_image": "Select a pest photo to analyze",
      "analyze_disease": "Analyze",
      "camera": "Camera",
      "gallery": "Gallery",
      "select_image_first": "Please select an image first",
      "result": "Result",
      "prediction_placeholder": "Prediction will appear here",
      "crop_recommendation": "Crop Recommendation",
      "temperature": "Temperature",
      "soil_ph": "Soil pH",
      "rainfall": "Rainfall",
      "recommend_crop": "Recommend Crop",
      "organic_remedy": "Organic Remedy",
      "chemical_remedy": "Chemical Remedy",
      "prevention": "Prevention",
      "confidence": "Confidence",
    },

    "te": {
      "login": "లాగిన్",
      "signup": "సైన్ అప్",
      "welcome_back": "మళ్లీ స్వాగతం",
      "create_account": "ఖాతా సృష్టించండి",
      "phone": "ఫోన్ నంబర్",
      "password": "పాస్వర్డ్",
      "name": "పేరు",
      "logout": "లాగ్ అవుట్",
      "profile": "ప్రొఫైల్",
      "save_changes": "మార్పులు సేవ్ చేయండి",
      "security": "భద్రత",
      "change_password": "పాస్వర్డ్ మార్చండి",
      "home": "హోమ్",
      "chat": "చాట్",
      "market": "మార్కెట్",
      "pest": "పీడకలు",
      "pest_analyzer": "పీడక విశ్లేషకుడు",
      "upload_leaf_image": "విశ్లేషించడానికి చిత్రాన్ని ఎంచుకోండి",
      "analyze_disease": "విశ్లేషించు",
      "camera": "కెమెరా",
      "gallery": "గ్యాలరీ",
      "select_image_first": "దయచేసి మొదట చిత్రాన్ని ఎంచుకోండి",
      "result": "ఫలితం",
      "prediction_placeholder": "అంచనా ఇక్కడ కనిపిస్తుంది",
      "crop_recommendation": "పంట సిఫార్సు",
      "temperature": "ఉష్ణోగ్రత",
      "soil_ph": "మట్టి pH",
      "rainfall": "వర్షపాతం",
      "recommend_crop": "పంటను సిఫారసు చేయండి",
      "organic_remedy": "సేంద్రీయ నివారణ",
      "chemical_remedy": "రసాయన నివారణ",
      "prevention": "నివారణ చర్యలు",
      "confidence": "నమ్మకం",
    },

    "hi": {
      "login": "लॉगिन",
      "signup": "साइन अप",
      "welcome_back": "वापसी पर स्वागत है",
      "create_account": "खाता बनाएं",
      "phone": "फ़ोन नंबर",
      "password": "पासवर्ड",
      "name": "नाम",
      "logout": "लॉग आउट",
      "profile": "प्रोफ़ाइल",
      "save_changes": "परिवर्तन सहेजें",
      "security": "सुरक्षा",
      "change_password": "पासवर्ड बदलें",
      "home": "होम",
      "chat": "चैट",
      "market": "बाज़ार",
      "pest": "कीट",
      "pest_analyzer": "कीट विश्लेषक",
      "upload_leaf_image": "विश्लेषण के लिए छवि चुनें",
      "analyze_disease": "विश्लेषण करें",
      "camera": "कैमरा",
      "gallery": "गैलरी",
      "select_image_first": "कृपया पहले एक छवि चुनें",
      "result": "परिणाम",
      "prediction_placeholder": "अनुमान यहाँ दिखेगा",
      "crop_recommendation": "फसल अनुशंसा",
      "temperature": "तापमान",
      "soil_ph": "मिट्टी pH",
      "rainfall": "वर्षा",
      "recommend_crop": "फसल की सिफारिश करें",
      "organic_remedy": "जैविक उपाय",
      "chemical_remedy": "रासायनिक उपाय",
      "prevention": "रोकथाम",
      "confidence": "विश्वास",
    },
  };
}
